import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by docusaurus-plugin-openapi-docs from ../apis/openapi.yaml.
// Regenerated on every build by the `prebuild` npm script, so the REST API
// Reference below is always the real, Spectral-validated spec — never a
// hand-transcribed copy of it.
import restApiSidebar from './docs/api/rest/sidebar';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      link: {type: 'doc', id: 'overview/index'},
      items: [
        'overview/what-it-does',
        'overview/hexagonal-layering',
        'overview/running-locally',
      ],
    },
    {
      type: 'category',
      label: 'Business Context',
      link: {type: 'doc', id: 'business-context/index'},
      items: [
        'business-context/domain-vision',
        'business-context/ubiquitous-language',
        'business-context/why-waveless-release',
        'business-context/flow-balancing',
      ],
    },
    {
      type: 'category',
      label: 'Domain-Driven Design',
      link: {type: 'doc', id: 'ddd/index'},
      items: [
        'ddd/subdomain-classification',
        'ddd/aggregates-and-invariants',
        'ddd/domain-events',
        'ddd/read-models',
        'ddd/context-relationships',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {type: 'doc', id: 'api/index'},
      items: [
        {
          type: 'category',
          label: 'REST API',
          link: {type: 'doc', id: 'api/rest-overview'},
          items: restApiSidebar,
        },
        'api/events',
        'api/errors',
      ],
    },
    {
      type: 'category',
      label: 'Ecosystem',
      link: {type: 'doc', id: 'ecosystem/index'},
      items: [
        'ecosystem/context-map',
        'ecosystem/integration-events',
        'ecosystem/sibling-services',
      ],
    },
    {
      type: 'category',
      label: 'AI Ecosystem (MCP)',
      collapsed: false,
      items: ['mcp/governance-charter'],
    },
    {
      type: 'category',
      label: 'Analytics (Data Product)',
      collapsed: false,
      items: ['analytics/release-throughput-report'],
    },
    {
      type: 'category',
      label: 'Architecture Decision Records',
      link: {type: 'doc', id: 'adr/index'},
      items: [
        'adr/0001-hexagonal-ports-and-adapters',
        'adr/0002-waveless-continuous-release',
        'adr/0003-flow-balancing-as-domain-service',
        'adr/0004-kafka-integration-events',
        'adr/0005-rfc-7807-problem-details',
        'adr/0006-labor-plan-view-not-shift-plan',
        'adr/0007-arch-go-fitness-tests',
        'adr/0008-mcp-inbound-adapter',
        'adr/0009-product-classification-propagation-to-work-released',
        'adr/0010-gift-wrap-as-a-work-released-characteristic',
        'adr/0011-analytical-data-product',
      ],
    },
  ],
};

export default sidebars;
